"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Clock3, Copy, Pause, Play, RefreshCw, Scissors, Send, Share2, Sparkles, X } from "lucide-react";
import type { AskAnswer, Meeting, SummarySection, SummaryTemplate } from "@/types/meeting";
import { formatDuration, formatMeetingDate } from "@/lib/formatters";
import { getTranscriptClip, type ShareableClip, type ShareableMoment } from "@/lib/sharing";
import { ShareDialog } from "@/components/share-dialog";

type Tab = "overview" | "transcript" | "actions" | "highlights" | "analytics";
const tabs: { id: Tab; label: string }[] = [
  { id: "overview", label: "Overview" }, { id: "transcript", label: "Transcript" },
  { id: "actions", label: "Actions" }, { id: "highlights", label: "Highlights" }, { id: "analytics", label: "Analytics" },
];
const questions = ["What were the main decisions?", "What should I follow up on?", "What risks were mentioned?"];

export function MeetingDetail({ meeting, initialTab = "overview" }: { meeting: Meeting; initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  const [time, setTime] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [template, setTemplate] = useState<SummaryTemplate>("enhanced");
  const [summary, setSummary] = useState(meeting.summaries);
  const [regenerating, setRegenerating] = useState(false);
  const [done, setDone] = useState(() => new Set(meeting.actionItems.filter((item) => item.completed).map((item) => item.id)));
  const [pending, setPending] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<AskAnswer | null>(null);
  const [answering, setAnswering] = useState(false);
  const [clipMode, setClipMode] = useState(false);
  const [clipStart, setClipStart] = useState<number | null>(null);
  const [clipEnd, setClipEnd] = useState<number | null>(null);
  const [creatingClip, setCreatingClip] = useState(false);
  const [sharedMoment, setSharedMoment] = useState<ShareableMoment | null | undefined>();
  const [sharedClip, setSharedClip] = useState<ShareableClip | undefined>();
  const [copied, setCopied] = useState(false);
  const transcriptRef = useRef<HTMLDivElement>(null);
  const current = meeting.transcript.findLastIndex((line) => line.startSeconds <= time);
  const selectedClip = useMemo(() => clipStart !== null && clipEnd !== null ? getTranscriptClip(meeting, meeting.transcript[clipStart]?.timestamp, meeting.transcript[clipEnd]?.timestamp) : undefined, [clipStart, clipEnd, meeting]);
  const talkTime = useMemo(() => { const map = new Map(meeting.participants.map((person) => [person.name, 0])); meeting.transcript.forEach((line) => map.set(line.speaker, (map.get(line.speaker) ?? 0) + Math.max(0, line.endSeconds - line.startSeconds))); const total = [...map.values()].reduce((a, b) => a + b, 0); return meeting.participants.map((person) => ({ person, seconds: map.get(person.name) ?? 0, pct: total ? Math.round(((map.get(person.name) ?? 0) / total) * 100) : 0 })); }, [meeting]);
  useEffect(() => { if (!playing) return; const interval = window.setInterval(() => setTime((value) => Math.min(meeting.durationSeconds, value + 0.25)), 250); return () => window.clearInterval(interval); }, [playing, meeting.durationSeconds]);
  useEffect(() => { if (time >= meeting.durationSeconds) { const timeout = window.setTimeout(() => setPlaying(false), 0); return () => window.clearTimeout(timeout); } }, [time, meeting.durationSeconds]);
  const jump = (seconds: number, nextTab?: Tab) => { setTime(seconds); if (nextTab) setTab(nextTab); if (nextTab === "transcript") window.setTimeout(() => transcriptRef.current?.querySelector(`[data-seconds="${seconds}"]`)?.scrollIntoView({ block: "center", behavior: "smooth" }), 50); };
  const toggleAction = async (id: string) => { if (pending) return; setPending(id); setError(""); try { const completed = !done.has(id); const response = await fetch(`/api/action-items/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ completed }) }); if (!response.ok) throw new Error("Could not update this action."); setDone((current) => { const next = new Set(current); if (completed) next.add(id); else next.delete(id); return next; }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update this action."); } finally { setPending(null); } };
  const regenerate = async () => { setRegenerating(true); setError(""); try { const response = await fetch(`/api/meetings/${meeting.id}/summaries/regenerate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ template }) }); if (!response.ok) throw new Error("Could not regenerate the brief."); const result = await response.json() as { summary: { content: SummarySection[] } }; setSummary((current) => ({ ...current, [template]: result.summary.content })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not regenerate the brief."); } finally { setRegenerating(false); } };
  const ask = async (text: string) => { if (!text.trim()) return; setAnswering(true); setAnswer(null); setError(""); try { const response = await fetch(`/api/meetings/${meeting.id}/ask`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: text.trim() }) }); if (!response.ok) throw new Error("Ask Relay could not answer right now."); const result = await response.json() as { answer: AskAnswer }; setAnswer(result.answer); } catch (cause) { setError(cause instanceof Error ? cause.message : "Ask Relay could not answer right now."); } finally { setAnswering(false); } };
  const selectTurn = (index: number) => { if (!clipMode) { jump(meeting.transcript[index].startSeconds); return; } if (clipStart === null || clipEnd !== null) { setClipStart(index); setClipEnd(null); } else { setClipStart(Math.min(clipStart, index)); setClipEnd(Math.max(clipStart, index)); } };
  const createClip = async () => { if (!selectedClip) return; setCreatingClip(true); setError(""); try { const response = await fetch("/api/clips", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ meetingId: meeting.id, startSeconds: meeting.transcript[clipStart!].startSeconds, endSeconds: meeting.transcript[clipEnd!].endSeconds }) }); if (!response.ok) throw new Error("Could not save the clip."); const result = await response.json() as { clip: { id: string } }; setSharedClip({ ...selectedClip, id: result.clip.id }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save the clip."); } finally { setCreatingClip(false); } };
  const copyQuote = async (text: string) => { try { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 2000); } catch { setError("Clipboard unavailable. Select the transcript text to copy it."); } };
  return <main className="relay-page meeting-workspace">
    <Link className="back-link" href="/meetings"><ArrowLeft size={16} /> All meetings</Link>
    <header className="workspace-hero"><div><p className="overline">MEETING / {meeting.id.toUpperCase()}</p><h1>{meeting.title}</h1><div className="hero-meta"><span>{formatMeetingDate(meeting.date)} · {meeting.time}</span><span>{formatDuration(meeting.durationSeconds)}</span><span>{meeting.participants.length} participants</span></div></div><button className="button primary" type="button" onClick={() => setSharedMoment(null)}><Share2 size={16} /> Share meeting</button></header>
    {error && <div role="alert" className="error-banner">{error}<button type="button" aria-label="Dismiss error" onClick={() => setError("")}><X size={16} /></button></div>}
    <section className="timeline-panel" aria-label="Simulated recording timeline"><div className="timeline-top"><div className="timeline-label"><span className="live-square" /> CONVERSATION TIMELINE <small>Transcript indexed · Playback simulation</small></div><span className="timeline-clock">{formatDuration(Math.floor(time))} <i>/</i> {formatDuration(meeting.durationSeconds)}</span></div><div className="timeline-controls"><button className="play-control" type="button" onClick={() => { if (time >= meeting.durationSeconds) setTime(0); setPlaying(!playing); }} aria-label={playing ? "Pause simulated playback" : "Play simulated playback"}>{playing ? <Pause size={17} fill="currentColor" /> : <Play size={17} fill="currentColor" />}</button><div className="timeline-track"><div className="timeline-segments" aria-hidden="true">{meeting.transcript.slice(0, 56).map((line, index) => <span key={line.id} className={index <= current ? "played" : ""} style={{ height: `${15 + ((index * 17) % 31)}px` }} />)}</div><input type="range" min="0" max={meeting.durationSeconds} step="1" value={time} onChange={(event) => jump(Number(event.target.value))} aria-label="Recording timeline" /><div className="timeline-flags">{meeting.highlights.map((highlight) => <button key={highlight.id} type="button" title={highlight.title} style={{ left: `${Math.min(100, (Number(highlight.timestamp.split(":").reduce((n, part) => n * 60 + Number(part), 0)) / meeting.durationSeconds) * 100)}%` }} onClick={() => jump(highlight.timestamp.split(":").reduce((n, part) => n * 60 + Number(part), 0), "transcript")} aria-label={`Jump to ${highlight.title} at ${highlight.timestamp}`} />)}</div></div></div></section>
    <div className="workspace-tabs" role="tablist" aria-label="Meeting views">{tabs.map(({ id, label }) => <button type="button" role="tab" key={id} aria-selected={tab === id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}{id === "actions" && <span>{meeting.actionItems.length - done.size}</span>}</button>)}</div>
    <div className="workspace-grid"><div className="workspace-main">
      {tab === "overview" && <><section className="brief-panel"><div className="section-head"><div><p className="overline">MEETING SYNTHESIS</p><h2>Executive brief</h2></div><div className="brief-controls"><select aria-label="Summary format" value={template} onChange={(event) => setTemplate(event.target.value as SummaryTemplate)}><option value="enhanced">Structured</option><option value="demo">Demo brief</option></select><button className="button subtle" type="button" onClick={regenerate} disabled={regenerating}><RefreshCw size={14} className={regenerating ? "spin" : ""} /> {regenerating ? "Regenerating" : "Regenerate"}</button></div></div><div className="brief-lead"><span className="overline">01 / THE CONVERSATION</span><p>{meeting.description || meeting.summary[0]?.body || "No meeting description available."}</p></div><div className="brief-sections">{(summary[template] ?? (template === "enhanced" ? meeting.summary : [])).map((section, index) => <article key={`${section.heading}-${index}`}><span className="section-index">{String(index + 1).padStart(2, "0")}</span><div><h3>{section.heading}</h3><p>{section.body}</p></div></article>)}</div></section><section className="overview-lower"><div className="section-head"><div><p className="overline">FOLLOW-THROUGH</p><h2>Next steps</h2></div><button className="text-link" type="button" onClick={() => setTab("actions")}>All actions <ArrowRight size={15} /></button></div>{meeting.actionItems.slice(0, 3).map((item) => <ActionRow key={item.id} item={item} checked={done.has(item.id)} disabled={pending === item.id} onToggle={() => toggleAction(item.id)} />)}{!meeting.actionItems.length && <p className="empty-note">No actions captured for this meeting.</p>}</section></>}
      {tab === "transcript" && <section className="transcript-panel-new"><div className="section-head"><div><p className="overline">SOURCE RECORD</p><h2>Transcript <span className="small-count">{meeting.transcript.length} turns</span></h2></div><button className={`button ${clipMode ? "primary" : "subtle"}`} type="button" onClick={() => { setClipMode(!clipMode); setClipStart(null); setClipEnd(null); }}>{clipMode ? <X size={15} /> : <Scissors size={15} />}{clipMode ? "Cancel selection" : "Create clip"}</button></div>{clipMode && <div className="clip-toolbar"><div><strong>{clipStart === null ? "Select the first turn" : clipEnd === null ? "Select the final turn" : `${selectedClip?.start}–${selectedClip?.endTime}`}</strong><small>{selectedClip ? `${selectedClip.lines.length} turns · ${formatDuration(selectedClip.durationSeconds)}` : "Choose a contiguous range in the transcript."}</small></div><button className="button primary" type="button" disabled={!selectedClip || creatingClip} onClick={createClip}>{creatingClip ? "Saving…" : "Save & share clip"}</button></div>}<div className="transcript-stream" ref={transcriptRef}>{meeting.transcript.map((line, index) => { const person = meeting.participants.find((p) => p.name === line.speaker); const selected = clipStart !== null && index >= clipStart && index <= (clipEnd ?? clipStart); const highlight = meeting.highlights.find((item) => item.timestamp === line.timestamp); const action = meeting.actionItems.find((item) => item.timestamp === line.timestamp); return <article className={`transcript-turn ${index === current ? "current" : ""} ${selected ? "selected" : ""}`} key={line.id} data-seconds={line.startSeconds}><button className="turn-time" type="button" onClick={() => selectTurn(index)} aria-label={`${clipMode ? "Select" : "Jump to"} transcript turn at ${line.timestamp}`}>{line.timestamp}</button><span className="person-avatar" style={{ background: person?.color ?? "#555" }}>{person?.initials ?? line.speaker.slice(0, 2)}</span><div className="turn-copy"><div className="speaker-line"><strong>{line.speaker}</strong><small>{person?.role}</small></div><p>{line.text}</p><div className="turn-tags">{highlight && <button type="button" onClick={() => setSharedMoment(highlight)}>✦ {highlight.title}</button>}{action && <span>↗ Action captured</span>}<button type="button" onClick={() => copyQuote(line.text)}><Copy size={12} /> {copied ? "Copied" : "Copy quote"}</button></div></div></article>; })}</div></section>}
      {tab === "actions" && <section className="white-panel"><div className="section-head"><div><p className="overline">ACCOUNTABILITY</p><h2>Action items</h2></div><span className="counter">{done.size}/{meeting.actionItems.length} complete</span></div><div className="action-list-new">{meeting.actionItems.map((item) => <ActionRow key={item.id} item={item} checked={done.has(item.id)} disabled={pending === item.id} onToggle={() => toggleAction(item.id)} />)}</div>{!meeting.actionItems.length && <p className="empty-note">No actions captured for this meeting.</p>}</section>}
      {tab === "highlights" && <section className="white-panel"><div className="section-head"><div><p className="overline">SHAREABLE MOMENTS</p><h2>Highlights</h2></div><span className="counter">{meeting.highlights.length}</span></div>{meeting.highlights.map((highlight) => <article className="highlight-entry" key={highlight.id}><span className="highlight-time">{highlight.timestamp}</span><div><h3>{highlight.title}</h3><p>{highlight.note}</p><div><button className="text-link" type="button" onClick={() => jump(highlight.timestamp.split(":").reduce((n, part) => n * 60 + Number(part), 0), "transcript")}>View in transcript <ArrowRight size={14} /></button><button className="text-link" type="button" onClick={() => setSharedMoment(highlight)}>Share moment <Share2 size={14} /></button></div></div></article>)}{!meeting.highlights.length && <p className="empty-note">No highlights captured for this meeting.</p>}</section>}
      {tab === "analytics" && <section className="white-panel"><div className="section-head"><div><p className="overline">CONVERSATION DYNAMICS</p><h2>Speaker distribution</h2></div></div><p className="panel-intro">Talk time is estimated from stored transcript turn boundaries.</p><div className="speaker-bars">{talkTime.map(({ person, seconds, pct }) => <div className="speaker-bar" key={person.id}><span className="person-avatar" style={{ background: person.color }}>{person.initials}</span><span className="speaker-name"><strong>{person.name}</strong><small>{person.role}</small></span><span className="bar-track"><i style={{ width: `${pct}%` }} /></span><strong>{pct}%</strong><small>{formatDuration(seconds)}</small></div>)}</div><div className="analytics-facts"><div><small>TRANSCRIPT TURNS</small><strong>{meeting.transcript.length}</strong></div><div><small>RECORDED LENGTH</small><strong>{formatDuration(meeting.durationSeconds)}</strong></div><div><small>PARTICIPANTS</small><strong>{meeting.participants.length}</strong></div></div></section>}
    </div><aside className="workspace-aside"><section className="context-panel"><p className="overline">IN THIS MEETING</p><h2>People & context</h2><div className="context-people">{meeting.participants.map((person) => <div key={person.id}><span className="person-avatar" style={{ background: person.color }}>{person.initials}</span><span><strong>{person.name}</strong><small>{person.role}</small></span></div>)}</div></section><section className="ask-panel"><div className="ask-heading"><Sparkles size={18} /><div><p className="overline">CONTEXTUAL Q&A</p><h2>Ask Relay</h2></div></div><p>Explore this meeting&apos;s stored notes, actions, and transcript. Answers use a rule-based demo endpoint.</p><div className="question-pills">{questions.map((q) => <button type="button" key={q} onClick={() => { setQuestion(q); ask(q); }} disabled={answering}>{q}</button>)}</div><form onSubmit={(event) => { event.preventDefault(); ask(question); }}><input aria-label="Question for Ask Relay" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about this meeting…" /><button type="submit" aria-label="Ask Relay" disabled={!question.trim() || answering}><Send size={16} /></button></form>{answering && <p role="status">Looking through meeting context…</p>}{answer && <div className="ask-result"><strong>RELAY RESPONSE</strong><p>{answer.text}</p>{answer.sources.map((source) => <button type="button" key={`${source.timestamp}-${source.label}`} onClick={() => jump(source.timestamp.split(":").reduce((n, part) => n * 60 + Number(part), 0), "transcript")}>{source.timestamp} · {source.label} <ArrowRight size={12} /></button>)}</div>}</section><section className="context-panel"><p className="overline">QUICK SIGNALS</p><div className="signal-stat"><span><Sparkles size={15} /> Highlights</span><strong>{meeting.highlights.length}</strong></div><div className="signal-stat"><span><Clock3 size={15} /> Saved clips</span><strong>{meeting.clips.length}</strong></div><div className="signal-stat"><span><Check size={15} /> Actions done</span><strong>{done.size}/{meeting.actionItems.length}</strong></div></section></aside></div>
    {sharedMoment !== undefined && <ShareDialog meeting={meeting} moment={sharedMoment ?? undefined} onClose={() => setSharedMoment(undefined)} />}
    {sharedClip && <ShareDialog meeting={meeting} clip={sharedClip} onClose={() => setSharedClip(undefined)} />}
  </main>;
}
function ActionRow({ item, checked, disabled, onToggle }: { item: Meeting["actionItems"][number]; checked: boolean; disabled: boolean; onToggle: () => void }) { return <div className={`relay-action ${checked ? "is-done" : ""}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={onToggle} aria-label={`Mark ${item.task} ${checked ? "incomplete" : "complete"}`} /><div><strong>{item.task}</strong>{item.description && <p>{item.description}</p>}<small>{item.owner}{item.due ? ` · Due ${item.due}` : ""}{item.timestamp ? ` · ${item.timestamp}` : ""}</small></div></div>; }
